### ISSUE TITLE
Criar a estrutura inicial

### ISSUE THREAD

**Issue by matmahnke** [matmahnke/isujou-service#2]
Criar a estrutura inicial do projeto em dotnet, utilizando os seguintes itens:
Criação da estrutura seguindo DDD e padrões de arquitetura;
Criação dos projetos em .net core 3.1;
Implementação inicial do Entity Framework Core com SQL Server;
Health check do banco de dados;
Documentação de API com Swagger;

**Comment by alanjantz** [comment]
Feito.
